// <auto-generated />
namespace HTLElectronics.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addiconcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addiconcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202207210436408_add-icon-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
